//
//
// contains constants to run the battery watchdog
//
//
// defaults

float PI_BATTERY_SHUTDOWN_THRESHOLD = 3.706; // 20%
float PI_BATTERY_STARTUP_THRESHOLD = 3.839; // 30%

float INSIDE_TEMPERATURE_PI_SHUTDOWN_THRESHOLD = 49.33; // 110
float INSIDE_TEMPERATURE_PI_STARTUP_THRESHOLD = 37.78; // 1000


float INSIDE_HUMIDITY_PI_SHUTDOWN_THRESHOLD = 98.0;
float INSIDE_HUMIDITY_PI_STARTUP_THRESHOLD = 93.0;



datetime PI_START_TIME;
datetime PI_SHUTDOWN_TIME;
float PI_MIDNIGHT_WAKEUP_SECONDS_LENGTH = 3600.0;   // one hour

float PI_MIDNIGHT_WAKEUP_THRESHOLD = 3.971;   // 60%
